# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIChat
  pod 'StreamChat', '~> 3.0.1'
end
